### ISSUE TITLE
Move to org

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/fr.javascript.info#9]
Hello @HachemiH !

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by HachemiH** [comment]
Hi @iliakan 

I tried to transfer to "javascript-tutorial" as you said, but i got this message : 
"You don’t have the permission to create repositories on javascript-tutorial"

It's ok to transfer this translation, but i can't, do you prefer clone it ?

**Comment by iliakan** [comment]
Please transfer to @iliakan , I'll move along.

**Comment by HachemiH** [comment]
Done
